application:
  name: prod环境 @artifactId@
  version: prod环境 @version@
developer:
  name: prod环境 jmw
  website: prod环境 https://www.jmwang-code.top/
  qq: prod环境 792836909
  phone-number: prod环境 792836909