spring:
  activiti:
    database-schema-update: update
    db-history-used: true
    copy-variables-to-local-for-tasks: false
    serialize-p-o-j-os-in-variables-to-json: false
    history-level: full
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.1.3:5236?schema=FLJD&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: SYSDBA