spring:
  activiti:
    #1.flase：默认值。activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    #2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    #3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    #4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true
    #检测历史表是否存在 activiti7默认没有开启数据库历史记录 启动数据库历史记录
    db-history-used: true
    #记录历史等级 可配置的历史级别有none, activity, audit, full
    #none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    #activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
    #audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
    #full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full
    #这个属性控制Activiti是否将流程变量复制到任务的本地变量。如果设置为false，Activiti将不会复制流程变量。
    copy-variables-to-local-for-tasks: false
    #这个属性控制Activiti是否将流程变量中的POJO对象序列化为JSON。如果设置为false，Activiti将不会序列化POJO对象。
    serialize-p-o-j-os-in-variables-to-json: false
    # false的话不扫描process下bpmn文件，true则会扫描并重新加载bpmn文件
    check-process-definitions: false
  security:
    user:
      name: admin
      password: admin

  datasource:
    # 8.+的驱动 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.154.249:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: activiti
    password: pxs8P3Sn2JJm8Pdj
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      #连接池做大连接数
#      maximum-pool-size: 30
#      #连接池空闲连接最小数量
#      #minimum-idle: 10
#      #允许连接在连接池中闲置最长时间
#      #idle-timeout: 30000
#      #池中连接最长生命周期
#      max-lifetime: 120000
#      #等待来自池的连接的最大毫秒数
#      connection-timeout: 30000



#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
