spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # DM 数据源配置
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.1.3:5236?schema=FLJD&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: SYSDBA
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置连接超时时间
    connectTimeout: 30000
    # 配置网络超时时间
    socketTimeout: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
#  transaction:
#    rollback-on-commit-failure: true
#  security:
#    custom:
#      commonTokenKey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoiMV82NTlmZGQ5NDI5NzY0OGMxYjdlZWQ5OTY5MWJiMjQ2NiJ9.3N-1JwEgFhIQBryCVzlBVwfKGtH2B7fy7QmrrAZelAg
  activiti:
    database-schema-update: update
    db-history-used: true
    copy-variables-to-local-for-tasks: false
    serialize-p-o-j-os-in-variables-to-json: false
    history-level: full
    # false的话不扫描process下bpmn文件，true则会扫描并重新加载bpmn文件
    #check-process-definitions: true
#  redis:
#    host: 192.168.1.3
#    port: 6379
#    database: 0
#    timeout: 10000
  #    password: 123456

server:
  port: 8080
# 开启Knife4j的增强模式
knife4j:
  enable: true


systemparam:
  defaultPassword: 123456
  adminUserId: 1
  zgjUnitId: 1
  token:
    payloadParam: payload
    defaultTokenSecret: chrome_19971205

