spring:
  datasource:
    url: jdbc:mysql://152.136.154.249:3306/information_schema?&allowMultiQueries=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db1
    password: SGTSKZ6jfHzPs6c7
  application:
    name: mybatis
  profiles:
    active: prod
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: 152.136.154.249:8848

server:
  port: 8081